function CreateLootingMessageWindow(id, parent)
  local chatWindow = UIParent:CreateWidget("message", id, parent)
  chatWindow.style:SetAlign(ALIGN_BOTTOM_LEFT)
  chatWindow.style:SetSnap(true)
  chatWindow.style:SetShadow(false)
  chatWindow:SetInset(ICON_SIZE.DEFAULT + 5, 0, 0, 2)
  chatWindow:SetMaxLines(1)
  chatWindow.style:SetColor(1, 1, 1, 1)
  chatWindow.style:SetFont(FONT_PATH.LEEYAGI, FONT_SIZE.XLARGE)
  return chatWindow
end
addedItemWindow = CreateLootingMessageWindow("addedItemWindow", systemLayerParent)
addedItemWindow:SetExtent(500, F_LAYOUT.CalcDontApplyUIScale(ICON_SIZE.DEFAULT))
addedItemWindow:AddAnchor("TOP", "UIParent", 0, 80)
addedItemWindow:Clickable(false)
addedItemWindow:Show(false)
local bg = CreateContentBackground(addedItemWindow, "TYPE8", "black")
addedItemWindow.bg = bg
local itemSlot = W_ICON.CreateItemIconImage("addedItemWindow.icon", systemLayerParent)
itemSlot:Show(false)
itemSlot:Clickable(false)
addedItemWindow.itemSlot = itemSlot
local itemName = addedItemWindow:CreateChildWidget("textbox", "itemName", 0, true)
itemName:Show(true)
itemName:SetExtent(500, FONT_SIZE.XLARGE)
itemName.style:SetSnap(true)
itemName.style:SetAlign(ALIGN_LEFT)
itemName.style:SetFont(FONT_PATH.LEEYAGI, FONT_SIZE.XLARGE)
ApplyTextColor(itemName, FONT_COLOR.WHITE)
function addedItemWindow:ResetPosition()
  itemSlot:RemoveAllAnchors()
  itemSlot:SetExtent(ICON_SIZE.DEFAULT, ICON_SIZE.DEFAULT)
  itemSlot:AddAnchor("LEFT", self, 0, 0)
  itemName:RemoveAllAnchors()
  itemName:AddAnchor("TOPLEFT", self, ICON_SIZE.DEFAULT + 5, 0)
end
addedItemWindow:ResetPosition()
