local CreateBestRatingRewardMessage = function(id, parent)
  local frame = CreateEmptyWindow(id, parent)
  frame:AddAnchor("TOP", parent, 0, 70)
  frame:SetSounds("dialog_common")
  SetttingUIAnimation(frame)
  local squareFrame = frame:CreateChildWidget("emptywidget", "squareFrame", 0, true)
  squareFrame:AddAnchor("TOPLEFT", frame, 0, 0)
  squareFrame:AddAnchor("BOTTOMRIGHT", frame, 0, 0)
  local bg = squareFrame:CreateDrawable(TEXTURE_PATH.GRADE_ENCHANT_ALARM, "bg_paper", "background")
  bg:AddAnchor("CENTER", squareFrame, 0, 0)
  frame:SetExtent(bg:GetWidth(), bg:GetHeight() + 10)
  local stateTexture = squareFrame:CreateDrawable(TEXTURE_PATH.BATTLEFIELD_BEST_RATING, "best_score", "background")
  stateTexture:AddAnchor("TOP", squareFrame, 0, MARGIN.WINDOW_SIDE)
  local informDesc = squareFrame:CreateChildWidget("textbox", "informDesc", 0, true)
  informDesc:SetExtent(frame:GetWidth() - MARGIN.WINDOW_SIDE * 4, FONT_SIZE.MIDDLE)
  informDesc:SetAutoResize(true)
  informDesc:SetHeight(FONT_SIZE.MIDDLE * 2)
  informDesc.style:SetFontSize(FONT_SIZE.MIDDLE)
  ApplyTextColor(informDesc, FONT_COLOR.DEFAULT)
  informDesc:AddAnchor("TOP", stateTexture, "BOTTOM", 0, 1)
  local ratingDiff = squareFrame:CreateChildWidget("emptywidget", "ratingDiff", 0, true)
  ratingDiff:SetExtent(261, 50)
  ratingDiff:AddAnchor("TOP", informDesc, "BOTTOM", 0, 12)
  local ratingbg = CreateContentBackground(ratingDiff, "TYPE2", "brown")
  ratingbg:AddAnchor("CENTER", ratingDiff, "CENTER", 0, 0)
  ratingbg:SetExtent(ratingDiff:GetWidth(), ratingDiff:GetHeight() + 10)
  local fieldName = ratingDiff:CreateChildWidget("label", "fieldName", 0, true)
  fieldName:SetAutoResize(true)
  fieldName:SetHeight(FONT_SIZE.LARGE)
  fieldName.style:SetFontSize(FONT_SIZE.LARGE)
  ApplyTextColor(fieldName, FONT_COLOR.BLUE)
  fieldName:AddAnchor("TOP", ratingDiff, "TOP", 0, MARGIN.WINDOW_SIDE / 4)
  local leftRating = ratingDiff:CreateChildWidget("label", "leftRating", 0, true)
  leftRating:SetAutoResize(true)
  leftRating:SetHeight(FONT_SIZE.XXLARGE)
  leftRating.style:SetFontSize(FONT_SIZE.XXLARGE)
  ApplyTextColor(leftRating, FONT_COLOR.BLUE)
  local ratingArrow = W_ICON.CreateArrowIcon(ratingDiff)
  ratingArrow:AddAnchor("TOP", fieldName, "BOTTOM", 0, MARGIN.WINDOW_SIDE / 3)
  ratingArrow:SetTextureColor("blue")
  ratingDiff.ratingArrow = ratingArrow
  leftRating:AddAnchor("RIGHT", ratingArrow, "LEFT", -5, 0)
  local rightRating = ratingDiff:CreateChildWidget("label", "rightRating", 0, true)
  rightRating:SetAutoResize(true)
  rightRating:SetHeight(FONT_SIZE.XXLARGE)
  rightRating.style:SetFontSize(FONT_SIZE.XXLARGE)
  ApplyTextColor(rightRating, FONT_COLOR.BLUE)
  rightRating:AddAnchor("LEFT", ratingArrow, "RIGHT", 5, 0)
  local rewardIcon = CreateItemIconButton(squareFrame:GetId() .. "rewardIcon", squareFrame)
  rewardIcon:SetExtent(ICON_SIZE.LARGE, ICON_SIZE.LARGE)
  rewardIcon:AddAnchor("TOP", ratingDiff, "BOTTOM", 0, MARGIN.WINDOW_SIDE / 2)
  squareFrame.rewardIcon = rewardIcon
  local rewardLabel = squareFrame:CreateChildWidget("label", "rewardLabel", 0, true)
  rewardLabel:SetAutoResize(true)
  rewardLabel:SetHeight(FONT_SIZE.LARGE)
  rewardLabel.style:SetFontSize(FONT_SIZE.LARGE)
  ApplyTextColor(rewardLabel, FONT_COLOR.DEFAULT)
  rewardLabel:AddAnchor("LEFT", rewardIcon, "RIGHT", MARGIN.WINDOW_SIDE / 3, 0)
  local okButton = squareFrame:CreateChildWidget("button", "okButton", 0, false)
  okButton:SetText(locale.common.ok)
  okButton:AddAnchor("BOTTOM", squareFrame, "BOTTOM", 0, -(MARGIN.WINDOW_SIDE * 2))
  ApplyButtonSkin(okButton, BUTTON_BASIC.DEFAULT)
  frame.isSet = false
  local function OkButtonLeftClickFunc()
    frame:Show(false)
    X2BattleField:ClearBestRatingReward()
  end
  ButtonOnClickHandler(okButton, OkButtonLeftClickFunc)
  function frame:SetReward(fieldName, oldRating, newRating, rewardType, rewardAmount)
    local itemInfo = X2Item:GetItemInfoByType(rewardType)
    self:SetStartAnimation(true, true)
    self.squareFrame.informDesc:SetText(X2Locale:LocalizeUiText(COMMON_TEXT, "best_rating_reward_ui_inform"))
    self.squareFrame.ratingDiff.fieldName:SetText(X2Locale:LocalizeUiText(COMMON_TEXT, "best_rating_reward_ui_title", fieldName))
    self.squareFrame.ratingDiff.leftRating:SetText(tostring(oldRating))
    self.squareFrame.ratingDiff.rightRating:SetText(tostring(newRating))
    self.squareFrame.rewardLabel:SetText(X2Locale:LocalizeUiText(COMMON_TEXT, "best_rating_reward_ui_reward", itemInfo.name, tostring(rewardAmount)))
    self.squareFrame.rewardIcon:SetItemInfo(itemInfo)
    self.squareFrame.rewardIcon:SetItemIcon(itemInfo.lookType, itemInfo.itemGrade)
    local xOffset = (self.squareFrame.rewardIcon:GetWidth() + MARGIN.WINDOW_SIDE / 3 + self.squareFrame.rewardLabel:GetWidth()) / 2
    self.squareFrame.rewardIcon:RemoveAllAnchors()
    self.squareFrame.rewardIcon:AddAnchor("TOPLEFT", self.squareFrame.ratingDiff, "BOTTOM", -xOffset, MARGIN.WINDOW_SIDE / 2)
    self.isSet = true
  end
  return frame
end
bestRatingRewardMessage = CreateBestRatingRewardMessage("bestRatingRewardMessage", "UIParent")
function ShowBestRatingRewardMessage()
  local rewardInfo = X2BattleField:GetBestRatingReward()
  if rewardInfo.hasReward then
    bestRatingRewardMessage:SetReward(rewardInfo.fieldName, rewardInfo.oldRating, rewardInfo.newRating, rewardInfo.rewardType, rewardInfo.rewardAmount)
    bestRatingRewardMessage:RemoveAllAnchors()
    bestRatingRewardMessage:AddAnchor("TOP", "UIParent", 0, 400)
    bestRatingRewardMessage:Show(true)
  else
    bestRatingRewardMessage:Show(false)
  end
end
UIParent:SetEventHandler("LEFT_LOADING", ShowBestRatingRewardMessage)
UIParent:SetEventHandler("ENTERED_WORLD", ShowBestRatingRewardMessage)
