function SetViewOfFamilyExpBar(tabWnd, anchor)
  local window = tabWnd:CreateChildWidget("emptywidget", "expBar", 0, true)
  window:Show(true)
  window:SetExtent(575, 14)
  window:AddAnchor("TOPLEFT", anchor, "BOTTOMLEFT", 0, 4)
  local statusBar = W_BAR.CreateStatusBar("dailyBar", window, "item_evolving_material")
  statusBar:AddAnchor("TOPLEFT", window, 1, 1)
  statusBar:AddAnchor("BOTTOMRIGHT", window, -1, -1)
  statusBar:SetMinMaxValues(0, 1000)
  statusBar:SetBarColor({
    ConvertColor(121),
    ConvertColor(177),
    ConvertColor(102),
    1
  })
  window.statusBar = statusBar
  local barEnd = window:CreateDrawable(TEXTURE_PATH.COMMUNITY_COMMON, "gage_bar", "overlay")
  window.barEnd = barEnd
  return window
end
function SetViewOfFamilyInfo(tabWnd)
  local sideMargin, titleMargin, bottomMargin = GetWindowMargin()
  local nameBg = tabWnd:CreateDrawable(TEXTURE_PATH.COMMUNITY_COMMON, "text_bg", "background")
  nameBg:AddAnchor("TOP", tabWnd, 0, 0)
  local nameLabel = tabWnd:CreateChildWidget("label", "nameLabel", 0, true)
  nameLabel:SetAutoResize(true)
  nameLabel:SetHeight(FONT_SIZE.XXLARGE)
  nameLabel.style:SetFont(FONT_PATH.LEEYAGI, FONT_SIZE.XXLARGE)
  nameLabel:AddAnchor("CENTER", nameBg, "CENTER", 0, 0)
  nameLabel.style:SetAlign(ALIGN_CENTER)
  ApplyTextColor(nameLabel, FONT_COLOR.DEFAULT)
  local picture = tabWnd:CreateDrawable(TEXTURE_PATH.FAMILY, "picture", "overlay")
  picture:AddAnchor("LEFT", tabWnd, 0, 0)
  picture:AddAnchor("TOP", nameBg, "BOTTOM", 0, 0)
  local bossLabel = tabWnd:CreateChildWidget("label", "bossLabel", 0, true)
  bossLabel:SetAutoResize(true)
  bossLabel:SetHeight(FONT_SIZE.LARGE)
  bossLabel.style:SetFontSize(FONT_SIZE.LARGE)
  bossLabel:AddAnchor("TOPLEFT", picture, "TOPRIGHT", 17, 0)
  bossLabel.style:SetAlign(ALIGN_LEFT)
  ApplyTextColor(bossLabel, FONT_COLOR.DEFAULT)
  local LevelTextbox = tabWnd:CreateChildWidget("textbox", "LevelTextbox", 0, true)
  LevelTextbox:SetAutoResize(true)
  LevelTextbox:SetWidth(200)
  LevelTextbox:SetHeight(FONT_SIZE.LARGE)
  LevelTextbox.style:SetFontSize(FONT_SIZE.LARGE)
  LevelTextbox:AddAnchor("TOPLEFT", bossLabel, "BOTTOMLEFT", 0, 15)
  LevelTextbox.style:SetAlign(ALIGN_LEFT)
  ApplyTextColor(LevelTextbox, FONT_COLOR.DEFAULT)
  local expBar = SetViewOfFamilyExpBar(tabWnd, LevelTextbox)
  tabWnd.expBar = expBar
  local titleLabel = tabWnd:CreateChildWidget("label", "titleLabel", 0, true)
  titleLabel:SetAutoResize(true)
  titleLabel:SetHeight(FONT_SIZE.LARGE)
  titleLabel.style:SetFontSize(FONT_SIZE.LARGE)
  titleLabel:AddAnchor("TOPLEFT", expBar, "BOTTOMLEFT", 0, 10)
  titleLabel.style:SetAlign(ALIGN_LEFT)
  ApplyTextColor(titleLabel, FONT_COLOR.DEFAULT)
  local roleLabel = tabWnd:CreateChildWidget("label", "roleLabel", 0, true)
  roleLabel:SetAutoResize(true)
  roleLabel:SetHeight(FONT_SIZE.LARGE)
  roleLabel.style:SetFontSize(FONT_SIZE.LARGE)
  roleLabel:AddAnchor("TOPLEFT", titleLabel, "BOTTOMLEFT", 0, 15)
  roleLabel.style:SetAlign(ALIGN_LEFT)
  ApplyTextColor(roleLabel, FONT_COLOR.DEFAULT)
  local icon = tabWnd:CreateImageDrawable(INVALID_ICON_PATH, "background")
  icon:AddAnchor("LEFT", roleLabel, "RIGHT", 15, 0)
  icon:SetCoords(0, 0, 28, 28)
  icon:SetExtent(28, 28)
  tabWnd.icon = icon
  local livingPointTextbox = tabWnd:CreateChildWidget("textbox", "livingPointTextbox", 0, true)
  livingPointTextbox:SetExtent(135, FONT_SIZE.LARGE)
  livingPointTextbox:SetWidth(500)
  livingPointTextbox.style:SetFontSize(FONT_SIZE.LARGE)
  livingPointTextbox:AddAnchor("TOPLEFT", roleLabel, "BOTTOMLEFT", 0, 15)
  livingPointTextbox.style:SetAlign(ALIGN_LEFT)
  ApplyTextColor(livingPointTextbox, FONT_COLOR.DEFAULT)
  local guideButton = tabWnd:CreateChildWidget("button", "guideButton", 0, true)
  ApplyButtonSkin(guideButton, BUTTON_BASIC.QUESTION_MARK)
  guideButton:AddAnchor("TOP", bossLabel, "TOP", 0, -4)
  guideButton:AddAnchor("RIGHT", tabWnd, "RIGHT", -4, 0)
  local memberCountTextbox = tabWnd:CreateChildWidget("textbox", "memberCountTextbox", 0, true)
  memberCountTextbox:SetAutoResize(true)
  memberCountTextbox:SetWidth(200)
  memberCountTextbox:SetHeight(FONT_SIZE.LARGE)
  memberCountTextbox.style:SetFontSize(FONT_SIZE.LARGE)
  memberCountTextbox:AddAnchor("TOPRIGHT", guideButton, "BOTTOMRIGHT", 0, 7)
  memberCountTextbox.style:SetAlign(ALIGN_RIGHT)
  ApplyTextColor(memberCountTextbox, FONT_COLOR.DEFAULT)
  local effectGuideButton = tabWnd:CreateChildWidget("button", "effectGuideButton", 0, true)
  ApplyButtonSkin(effectGuideButton, BUTTON_BASIC.QUESTION_MARK)
  effectGuideButton:AddAnchor("TOPRIGHT", memberCountTextbox, "BOTTOMRIGHT", 0, 7)
  local nameChangeButton = tabWnd:CreateChildWidget("button", "nameChangeButton", 0, true)
  nameChangeButton:SetText(GetCommonText("family_name_change"))
  nameChangeButton:AddAnchor("TOPRIGHT", effectGuideButton, "BOTTOMRIGHT", 0, 15)
  ApplyButtonSkin(nameChangeButton, BUTTON_BASIC.DEFAULT)
  local livingShopButton = tabWnd:CreateChildWidget("button", "livingShopButton", 0, true)
  livingShopButton:SetText(GetCommonText("family_living_point_shop"))
  livingShopButton:AddAnchor("TOPRIGHT", nameChangeButton, "BOTTOMRIGHT", 0, 5)
  ApplyButtonSkin(livingShopButton, BUTTON_BASIC.DEFAULT)
  local writeButton = tabWnd:CreateChildWidget("button", "writeButton", 0, true)
  ApplyButtonSkin(writeButton, BUTTON_CONTENTS.FAMILY_INFO_WRITE)
  writeButton:AddAnchor("BOTTOMRIGHT", tabWnd, 0, 10)
  local contentBg = CreateContentBackground(tabWnd, "TYPE2", "orange")
  contentBg:AddAnchor("TOPLEFT", picture, "BOTTOMLEFT", 0, 22)
  contentBg:AddAnchor("BOTTOMRIGHT", writeButton, "TOPRIGHT", 0, -16)
  local content1 = W_CTRL.CreateMultiLineEdit("content1", tabWnd)
  content1:SetExtent(765, 80)
  content1:AddAnchor("TOPLEFT", contentBg, "TOPLEFT", 10, 10)
  ApplyTextColor(content1, FONT_COLOR.BLUE)
  content1:SetInset(10, 10, 15, 10)
  content1.textLength = 136
  content1:SetMaxTextLength(content1.textLength)
  content1:Enable(false)
  content1:SetReadOnly(true)
  content1.bg:Show(false)
  local content1Label = tabWnd:CreateChildWidget("textbox", "content1Label", 0, true)
  content1Label:SetHeight(FONT_SIZE.LARGE)
  content1Label.style:SetFontSize(FONT_SIZE.LARGE)
  content1Label:AddAnchor("TOPRIGHT", contentBg, -13, 15)
  content1Label:AddAnchor("LEFT", content1, "RIGHT", 0, 0)
  content1Label.style:SetAlign(ALIGN_RIGHT)
  ApplyTextColor(content1Label, FONT_COLOR.SOFT_BROWN)
  content1Label:Show(false)
  local contentLine = CreateLine(tabWnd, "TYPE1")
  contentLine:AddAnchor("TOP", content1, "BOTTOM", 0, 15)
  contentLine:AddAnchor("LEFT", contentBg, 0, 0)
  contentLine:AddAnchor("RIGHT", contentBg, 0, 0)
  local content2 = W_CTRL.CreateMultiLineEdit("content2", tabWnd)
  content2:SetExtent(765, 110)
  content2:AddAnchor("TOPLEFT", contentLine, "BOTTOMLEFT", 10, 10)
  ApplyTextColor(content2, FONT_COLOR.DEFAULT)
  content2:SetInset(10, 10, 15, 10)
  content2.textLength = 200
  content2:SetMaxTextLength(content2.textLength)
  content2:Enable(false)
  content2:SetReadOnly(true)
  content2.bg:Show(false)
  local content2Label = tabWnd:CreateChildWidget("textbox", "content2Label", 0, true)
  content2Label:SetHeight(FONT_SIZE.LARGE)
  content2Label.style:SetFontSize(FONT_SIZE.LARGE)
  content2Label:AddAnchor("TOPRIGHT", contentLine, "BOTTOMRIGHT", -13, 10)
  content2Label:AddAnchor("LEFT", content2, "RIGHT", 0, 0)
  content2Label.style:SetAlign(ALIGN_RIGHT)
  ApplyTextColor(content2Label, FONT_COLOR.SOFT_BROWN)
  content2Label:Show(false)
  tabWnd:Show(false)
end
