function SetViewOfFamilyDlgChangeName(id, parent)
  local sideMargin, titleMargin, bottomMargin = GetWindowMargin()
  local window = CreateWindow(id, parent)
  window:SetExtent(430, 360)
  window:AddAnchor("CENTER", parent, 0, 0)
  window:SetTitle(GetCommonText("family_name_change"))
  local centerWidget = window:CreateChildWidget("emptywidget", "expBar", 0, true)
  centerWidget:AddAnchor("TOPLEFT", window, "TOPLEFT", sideMargin + 15, titleMargin)
  centerWidget:AddAnchor("BOTTOMRIGHT", window, "BOTTOMRIGHT", -(sideMargin + 15), -sideMargin)
  local nameLabel = window:CreateChildWidget("label", "nameLabel", 0, true)
  nameLabel:SetAutoResize(true)
  nameLabel:SetHeight(FONT_SIZE.LARGE)
  nameLabel.style:SetFontSize(FONT_SIZE.LARGE)
  nameLabel:AddAnchor("TOPLEFT", centerWidget, "TOPLEFT", 0, 12)
  nameLabel.style:SetAlign(ALIGN_LEFT)
  ApplyTextColor(nameLabel, FONT_COLOR.DEFAULT)
  nameLabel:SetText(GetCommonText("family_name"))
  local name = window:CreateChildWidget("label", "name", 0, true)
  name:SetAutoResize(true)
  name:SetHeight(FONT_SIZE.MIDDLE)
  name.style:SetFontSize(FONT_SIZE.MIDDLE)
  name:AddAnchor("TOPLEFT", nameLabel, "BOTTOMLEFT", 0, 6)
  name.style:SetAlign(ALIGN_LEFT)
  ApplyTextColor(name, FONT_COLOR.DEFAULT)
  local changeNameLabel = window:CreateChildWidget("label", "changeNameTextbox", 0, true)
  changeNameLabel:SetAutoResize(true)
  changeNameLabel:SetHeight(FONT_SIZE.LARGE)
  changeNameLabel.style:SetFontSize(FONT_SIZE.LARGE)
  changeNameLabel:AddAnchor("TOPLEFT", name, "BOTTOMLEFT", 0, 20)
  changeNameLabel.style:SetAlign(ALIGN_LEFT)
  ApplyTextColor(changeNameLabel, FONT_COLOR.DEFAULT)
  changeNameLabel:SetText(GetCommonText("family_name_change_input"))
  local namePolicyInfo = X2Util:GetNamePolicyInfo(VNT_FAMILY)
  local changeNameGuideTextbox = window:CreateChildWidget("textbox", "changeNameGuideTextbox", 0, true)
  changeNameGuideTextbox:SetExtent(centerWidget:GetWidth(), FONT_SIZE.MIDDLE)
  changeNameGuideTextbox:SetAutoResize(true)
  changeNameGuideTextbox:SetAutoWordwrap(true)
  changeNameGuideTextbox.style:SetFontSize(FONT_SIZE.MIDDLE)
  changeNameGuideTextbox.style:SetAlign(ALIGN_LEFT)
  changeNameGuideTextbox:AddAnchor("TOPLEFT", changeNameLabel, "BOTTOMLEFT", 0, 5)
  ApplyTextColor(changeNameGuideTextbox, FONT_COLOR.GRAY)
  changeNameGuideTextbox:SetText(F_TEXT.GetLimitInfoText(namePolicyInfo))
  local inputNameEdit = W_CTRL.CreateEdit("inputNameEdit", window)
  inputNameEdit:SetExtent(centerWidget:GetWidth(), DEFAULT_SIZE.EDIT_HEIGHT)
  inputNameEdit:AddAnchor("TOPLEFT", changeNameGuideTextbox, "BOTTOMLEFT", 0, 5)
  inputNameEdit:SetMaxTextLength(namePolicyInfo.max)
  local rejoinWaiting = window:CreateChildWidget("label", "rejoinWaiting", 0, true)
  rejoinWaiting:SetAutoResize(true)
  rejoinWaiting:AddAnchor("TOP", inputNameEdit, "BOTTOM", 0, 12)
  ApplyTextColor(rejoinWaiting, FONT_COLOR.RED)
  window.itemBtn = CreateItemIconButton("itemBtn", window)
  window.itemBtn:AddAnchor("TOP", inputNameEdit, "BOTTOM", 0, 30)
  local itemTextbox = window:CreateChildWidget("textbox", "itemTextbox", 0, true)
  itemTextbox:SetExtent(DEFAULT_SIZE.DIALOG_CONTENT_WIDTH, 35)
  itemTextbox.style:SetAlign(ALIGN_CENTER)
  itemTextbox.style:SetFont(FONT_PATH.DEFAULT, FONT_SIZE.LARGE)
  ApplyTextColor(itemTextbox, FONT_COLOR.TITLE)
  itemTextbox:AddAnchor("TOP", window.itemBtn, "BOTTOM", 0, 0)
  local okButton = window:CreateChildWidget("button", "okButton", 0, true)
  okButton:SetText(GetCommonText("ok"))
  ApplyButtonSkin(okButton, BUTTON_BASIC.DEFAULT)
  okButton:AddAnchor("BOTTOM", centerWidget, "BOTTOM", -okButton:GetWidth() / 2, 0)
  local cancelButton = window:CreateChildWidget("button", "cancelButton", 0, true)
  cancelButton:SetText(GetCommonText("cancel"))
  ApplyButtonSkin(cancelButton, BUTTON_BASIC.DEFAULT)
  cancelButton:AddAnchor("BOTTOM", centerWidget, "BOTTOM", cancelButton:GetWidth() / 2, 0)
  return window
end
