function SetViewOfGradeUpDownFrame(id, parent)
  local sideMargin, titleMargin, bottomMargin = GetWindowMargin()
  local window = CreateWindow(id, parent)
  window:SetCloseOnEscape(true, true)
  window:SetExtent(WINDOW_SIZE.SMALL, 260)
  window:AddAnchor("CENTER", "UIParent", 0, 0)
  window:SetTitle(locale.premium.premium_grade)
  local gradeExplanationLabel = window:CreateChildWidget("label", "gradeExplanationLabel", 0, true)
  gradeExplanationLabel:SetExtent(200, 20)
  gradeExplanationLabel.style:SetFont(FONT_PATH.DEFAULT, FONT_SIZE.MIDDLE)
  gradeExplanationLabel.style:SetColor(FONT_COLOR.BROWN[1], FONT_COLOR.BROWN[2], FONT_COLOR.BROWN[3], 1)
  gradeExplanationLabel:AddAnchor("CENTER", window, 0, -70)
  local gradeLabel = window:CreateChildWidget("label", "gradeLabel", 0, true)
  gradeLabel:SetExtent(30, 30)
  gradeLabel.style:SetFont("characterInfo", 37)
  gradeLabel:AddAnchor("CENTER", window, 0, -10)
  local gradeArrow = gradeLabel:CreateDrawable(TEXTURE_PATH.PREMIUM_SERVICE_GRADE_ARROW, "upgrade", "background")
  gradeArrow:SetExtent(96, 84)
  gradeArrow:AddAnchor("CENTER", gradeLabel, 0, 0)
  gradeNumColor = F_COLOR.GetColor("original_dark_orange", false)
  local prevGradeNumLabel = window:CreateChildWidget("label", "prevGradeNumLabel", 0, true)
  prevGradeNumLabel:SetExtent(80, 27)
  prevGradeNumLabel.style:SetFont(FONT_PATH.DEFAULT, FONT_SIZE.LARGE)
  prevGradeNumLabel.style:SetColor(gradeNumColor[1], gradeNumColor[2], gradeNumColor[3], gradeNumColor[4])
  prevGradeNumLabel:AddAnchor("CENTER", window, -40, 40)
  local presentGradeNumLabel = window:CreateChildWidget("label", "presentGradeNumLabel", 0, true)
  presentGradeNumLabel:SetExtent(80, 27)
  presentGradeNumLabel.style:SetFont(FONT_PATH.DEFAULT, FONT_SIZE.LARGE)
  presentGradeNumLabel.style:SetColor(gradeNumColor[1], gradeNumColor[2], gradeNumColor[3], gradeNumColor[4])
  presentGradeNumLabel:AddAnchor("CENTER", window, 30, 40)
  local gradeChangeArrow = W_ICON.CreateArrowIcon(window)
  gradeChangeArrow:AddAnchor("CENTER", window, -8, 40)
  gradeChangeArrow:SetTextureColor("dark_brown")
  local okBtn = window:CreateChildWidget("button", "okBtn", 0, true)
  okBtn:Enable(true)
  okBtn:AddAnchor("BOTTOMLEFT", window, 110, -25)
  okBtn:AddAnchor("BOTTOMRIGHT", window, -110, -25)
  okBtn:SetText(locale.common.ok)
  ApplyButtonSkin(okBtn, BUTTON_BASIC.DEFAULT)
  function okBtn:OnClick()
    window:Show(false)
  end
  okBtn:SetHandler("OnClick", okBtn.OnClick)
  function ViewUpDownGrade(prevGrade, presentGrade)
    if prevGrade < presentGrade then
      gradeExplanationLabel:SetText(locale.premium.upgrade_premium)
      gradeArrow:SetTextureInfo("upgrade")
      gradeLabel:SetText(tostring(presentGrade - 1))
      gradeLabel.style:SetColor(ConvertColor(60), ConvertColor(125), ConvertColor(159), 1)
      prevGradeNumLabel:SetText(locale.premium.grade(tostring(prevGrade - 1)))
      presentGradeNumLabel:SetText(locale.premium.grade(tostring(presentGrade - 1)))
    elseif presentGrade < prevGrade then
      gradeExplanationLabel:SetText(locale.premium.downgrade_premium)
      gradeArrow:SetTextureInfo("downgrade")
      gradeLabel:SetText(tostring(presentGrade - 1))
      gradeLabel.style:SetColor(ConvertColor(146), ConvertColor(90), ConvertColor(107), 1)
      prevGradeNumLabel:SetText(locale.premium.grade(tostring(prevGrade - 1)))
      presentGradeNumLabel:SetText(locale.premium.grade(tostring(presentGrade - 1)))
    end
  end
  return window
end
