function SetViewOfRaidApplicant(id, parent)
  local sideMargin, titleMargin, bottomMargin = GetWindowMargin()
  local wnd = CreateWindow(id, "UIParent")
  wnd:SetExtent(510, 569)
  wnd:AddAnchor("CENTER", "UIParent", 0, 0)
  wnd:SetTitle(GetCommonText("raid_applicant"))
  wnd:Show(true)
  parent.recruitmentWnd = wnd
  local emptyBottomMagin = bottomMargin - 120
  local bottomWidget_y = 0
  local leftWidget = wnd:CreateChildWidget("emptywidget", "emptywidget", 0, false)
  leftWidget:AddAnchor("TOPLEFT", wnd, "TOPLEFT", sideMargin, titleMargin)
  leftWidget:AddAnchor("BOTTOMRIGHT", wnd, "BOTTOMRIGHT", -(wnd:GetWidth() / 3) * 2, emptyBottomMagin)
  local topLeftWidget = wnd:CreateChildWidget("emptywidget", "topLeftWidget", 0, false)
  topLeftWidget:AddAnchor("TOPLEFT", leftWidget, "TOPLEFT", 0, 0)
  topLeftWidget:AddAnchor("BOTTOMRIGHT", leftWidget, "BOTTOMRIGHT", 0, -leftWidget:GetHeight() / 2)
  local bottomLeftWidget = wnd:CreateChildWidget("emptywidget", "bottomLeftWidget", 0, false)
  bottomLeftWidget:AddAnchor("TOPLEFT", topLeftWidget, "BOTTOMLEFT", 0, bottomWidget_y)
  bottomLeftWidget:AddAnchor("BOTTOMRIGHT", leftWidget, "BOTTOMRIGHT", 0, 0)
  local bg = CreateContentBackground(wnd, "TYPE2", "brown")
  bg:AddAnchor("TOPLEFT", topLeftWidget, 0, 0)
  bg:AddAnchor("BOTTOMRIGHT", topLeftWidget, 0, 0)
  local bg = CreateContentBackground(wnd, "TYPE2", "brown")
  bg:AddAnchor("TOPLEFT", bottomLeftWidget, 0, 0)
  bg:AddAnchor("BOTTOMRIGHT", bottomLeftWidget, 0, 0)
  local roleBg = CreateContentBackground(wnd, "TYPE2", "brown")
  roleBg:AddAnchor("TOPLEFT", bottomLeftWidget, "BOTTOMLEFT", 0, bottomWidget_y)
  roleBg:AddAnchor("BOTTOMRIGHT", bottomLeftWidget, 0, 60)
  local rightWidget = wnd:CreateChildWidget("emptywidget", "rightWidget", 0, false)
  rightWidget:AddAnchor("TOPLEFT", leftWidget, "TOPRIGHT", 4, 0)
  rightWidget:AddAnchor("BOTTOMRIGHT", wnd, "BOTTOMRIGHT", -sideMargin, emptyBottomMagin)
  local topRightWidget = wnd:CreateChildWidget("emptywidget", "topRightWidget", 0, false)
  topRightWidget:AddAnchor("TOPLEFT", rightWidget, "TOPLEFT", 0, 0)
  topRightWidget:AddAnchor("BOTTOMRIGHT", rightWidget, "BOTTOMRIGHT", 0, -rightWidget:GetHeight() / 2)
  local bottomRightWidget = wnd:CreateChildWidget("emptywidget", "bottomRightWidget", 0, false)
  bottomRightWidget:AddAnchor("TOPLEFT", topRightWidget, "BOTTOMLEFT", 0, bottomWidget_y)
  bottomRightWidget:AddAnchor("BOTTOMRIGHT", rightWidget, "BOTTOMRIGHT", 0, 0)
  local recruitTypeLabel = wnd:CreateChildWidget("label", "recruitTypeLabal", 0, true)
  recruitTypeLabel:SetAutoResize(true)
  recruitTypeLabel:SetHeight(FONT_SIZE.LARGE)
  recruitTypeLabel.style:SetAlign(ALIGN_CENTER)
  recruitTypeLabel.style:SetFontSize(FONT_SIZE.LARGE)
  recruitTypeLabel:AddAnchor("TOPLEFT", topLeftWidget, "TOPLEFT", 0, 18)
  recruitTypeLabel:AddAnchor("TOPRIGHT", topLeftWidget, "TOPRIGHT", 0, 0)
  recruitTypeLabel:SetText(GetCommonText("raid_type"))
  ApplyTextColor(recruitTypeLabel, FONT_COLOR.DEFAULT)
  local descriptionLabel = wnd:CreateChildWidget("label", "descriptionLabel", 0, true)
  descriptionLabel:SetAutoResize(true)
  descriptionLabel:SetHeight(FONT_SIZE.MIDDLE)
  descriptionLabel.style:SetAlign(ALIGN_CENTER)
  descriptionLabel.style:SetFontSize(FONT_SIZE.MIDDLE)
  descriptionLabel:AddAnchor("TOPLEFT", recruitTypeLabel, "BOTTOMLEFT", 0, 15)
  descriptionLabel:AddAnchor("TOPRIGHT", recruitTypeLabel, "TOPRIGHT", 0, 0)
  descriptionLabel:SetText(GetCommonText("raid_description"))
  ApplyTextColor(descriptionLabel, FONT_COLOR.DEFAULT)
  local levelLimitLabel = wnd:CreateChildWidget("label", "levelLimitLabel", 0, true)
  levelLimitLabel:SetAutoResize(true)
  levelLimitLabel:SetHeight(FONT_SIZE.LARGE)
  levelLimitLabel.style:SetAlign(ALIGN_CENTER)
  levelLimitLabel.style:SetFontSize(FONT_SIZE.LARGE)
  levelLimitLabel:AddAnchor("TOPLEFT", descriptionLabel, "BOTTOMLEFT", 0, 51)
  levelLimitLabel:AddAnchor("TOPRIGHT", descriptionLabel, "TOPRIGHT", 0, 0)
  levelLimitLabel:SetText(GetCommonText("raid_level_limit"))
  ApplyTextColor(levelLimitLabel, FONT_COLOR.DEFAULT)
  local departureTimeLabel = wnd:CreateChildWidget("label", "departureTimeLabel ", 0, true)
  departureTimeLabel:SetAutoResize(true)
  departureTimeLabel:SetHeight(FONT_SIZE.LARGE)
  departureTimeLabel.style:SetAlign(ALIGN_CENTER)
  departureTimeLabel.style:SetFontSize(FONT_SIZE.LARGE)
  departureTimeLabel:AddAnchor("TOPLEFT", levelLimitLabel, "BOTTOMLEFT", 0, 12)
  departureTimeLabel:AddAnchor("TOPRIGHT", levelLimitLabel, "TOPRIGHT", 0, 0)
  departureTimeLabel:SetText(GetCommonText("raid_departure_time"))
  ApplyTextColor(departureTimeLabel, FONT_COLOR.DEFAULT)
  local typeIcon = wnd:CreateImageDrawable(TEXTURE_PATH.RAID_RECRUIT, "overlay")
  typeIcon:AddAnchor("TOPLEFT", topRightWidget, "TOPLEFT", 0, 14)
  wnd.typeIcon = typeIcon
  local recruitSubType = wnd:CreateChildWidget("label", "recruitSubType", 0, true)
  recruitSubType:SetAutoResize(true)
  recruitSubType:SetHeight(FONT_SIZE.MIDDLE)
  recruitSubType.style:SetAlign(ALIGN_CENTER)
  recruitSubType.style:SetFontSize(FONT_SIZE.MIDDLE)
  recruitSubType:AddAnchor("LEFT", typeIcon, "RIGHT", 4, 0)
  recruitSubType:SetText(GetCommonText("raid_type"))
  ApplyTextColor(recruitSubType, FONT_COLOR.BLUE)
  local bg = CreateContentBackground(wnd, "TYPE2", "orange")
  bg:AddAnchor("TOPLEFT", typeIcon, "BOTTOMLEFT", -4, 2)
  bg:AddAnchor("BOTTOMRIGHT", topRightWidget, "BOTTOMRIGHT", 4, -60)
  local description = wnd:CreateChildWidget("textbox", "description", 0, true)
  description:SetAutoResize(true)
  description:SetHeight(FONT_SIZE.MIDDLE)
  description:SetLineSpace(TEXTBOX_LINE_SPACE.SMALL)
  description.style:SetAlign(ALIGN_TOP_LEFT)
  description.style:SetFontSize(FONT_SIZE.MIDDLE)
  description:AddAnchor("TOPLEFT", bg, "TOPLEFT", 10, 10)
  description:AddAnchor("BOTTOMRIGHT", bg, "BOTTOMRIGHT", -10, -10)
  ApplyTextColor(description, FONT_COLOR.DEFAULT)
  local levelLimit = wnd:CreateChildWidget("textbox", "levelLimit", 0, true)
  levelLimit:SetAutoResize(true)
  levelLimit:SetExtent(200, FONT_SIZE.MIDDLE)
  levelLimit.style:SetAlign(ALIGN_LEFT)
  levelLimit.style:SetFontSize(FONT_SIZE.MIDDLE)
  levelLimit:AddAnchor("TOPLEFT", description, "BOTTOMLEFT", 0, 17)
  ApplyTextColor(levelLimit, FONT_COLOR.BLUE)
  local departureTime = wnd:CreateChildWidget("label", "departureTime", 0, true)
  departureTime:SetAutoResize(true)
  departureTime:SetHeight(FONT_SIZE.MIDDLE)
  departureTime.style:SetAlign(ALIGN_LEFT)
  departureTime.style:SetFontSize(FONT_SIZE.MIDDLE)
  departureTime:AddAnchor("TOPLEFT", levelLimit, "BOTTOMLEFT", 0, 14)
  ApplyTextColor(departureTime, FONT_COLOR.BLUE)
  local ownerNameLabel = wnd:CreateChildWidget("label", "ownerNameLabel", 0, true)
  ownerNameLabel:SetAutoResize(true)
  ownerNameLabel:SetHeight(FONT_SIZE.LARGE)
  ownerNameLabel.style:SetAlign(ALIGN_CENTER)
  ownerNameLabel.style:SetFontSize(FONT_SIZE.LARGE)
  ownerNameLabel:AddAnchor("TOPLEFT", bottomLeftWidget, "TOPLEFT", 0, 20)
  ownerNameLabel:AddAnchor("TOPRIGHT", bottomLeftWidget, "TOPRIGHT", 0, 0)
  ownerNameLabel:SetText(X2Locale:LocalizeUiText(RAID_TEXT, "raid_owner"))
  ApplyTextColor(ownerNameLabel, FONT_COLOR.DEFAULT)
  local ownerLevelLabel = wnd:CreateChildWidget("label", "ownerLevelLabel", 0, true)
  ownerLevelLabel:SetAutoResize(true)
  ownerLevelLabel:SetHeight(FONT_SIZE.MIDDLE)
  ownerLevelLabel.style:SetAlign(ALIGN_CENTER)
  ownerLevelLabel.style:SetFontSize(FONT_SIZE.MIDDLE)
  ownerLevelLabel:AddAnchor("TOPLEFT", ownerNameLabel, "BOTTOMLEFT", 0, 13)
  ownerLevelLabel:AddAnchor("TOPRIGHT", ownerNameLabel, "TOPRIGHT", 0, 0)
  ownerLevelLabel:SetText(GetCommonText("level"))
  ApplyTextColor(ownerLevelLabel, FONT_COLOR.DEFAULT)
  local ownerExpeditionLabel = wnd:CreateChildWidget("label", "ownerExpeditionLabel", 0, true)
  ownerExpeditionLabel:SetAutoResize(true)
  ownerExpeditionLabel:SetHeight(FONT_SIZE.MIDDLE)
  ownerExpeditionLabel.style:SetAlign(ALIGN_CENTER)
  ownerExpeditionLabel.style:SetFontSize(FONT_SIZE.MIDDLE)
  ownerExpeditionLabel:AddAnchor("TOPLEFT", ownerLevelLabel, "BOTTOMLEFT", 0, 11)
  ownerExpeditionLabel:AddAnchor("TOPRIGHT", ownerLevelLabel, "TOPRIGHT", 0, 0)
  ownerExpeditionLabel:SetText(GetCommonText("expedition"))
  ApplyTextColor(ownerExpeditionLabel, FONT_COLOR.DEFAULT)
  local guideLabel = wnd:CreateChildWidget("label", "guideLabel", 0, true)
  guideLabel:SetAutoResize(true)
  guideLabel:SetHeight(FONT_SIZE.LARGE)
  guideLabel.style:SetAlign(ALIGN_CENTER)
  guideLabel.style:SetFontSize(FONT_SIZE.LARGE)
  guideLabel:AddAnchor("TOPLEFT", ownerExpeditionLabel, "BOTTOMLEFT", 0, 20)
  guideLabel:AddAnchor("TOPRIGHT", ownerExpeditionLabel, "TOPRIGHT", 0, 0)
  guideLabel:SetText(GetCommonText("raid_guide"))
  ApplyTextColor(guideLabel, FONT_COLOR.DEFAULT)
  local roleLabel = wnd:CreateChildWidget("label", "roleLabel", 0, true)
  roleLabel:SetAutoResize(true)
  roleLabel:SetHeight(FONT_SIZE.LARGE)
  roleLabel.style:SetAlign(ALIGN_CENTER)
  roleLabel.style:SetFontSize(FONT_SIZE.LARGE)
  roleLabel:AddAnchor("TOPLEFT", roleBg, "TOPLEFT", 0, 0)
  roleLabel:AddAnchor("BOTTOMRIGHT", roleBg, "BOTTOMRIGHT", 0, 0)
  ApplyTextColor(roleLabel, FONT_COLOR.DEFAULT)
  roleLabel:SetText(X2Locale:LocalizeUiText(RAID_TEXT, "set_my_role"))
  local ownerName = wnd:CreateChildWidget("label", "ownerName", 0, true)
  ownerName:SetAutoResize(true)
  ownerName:SetHeight(FONT_SIZE.MIDDLE)
  ownerName.style:SetAlign(ALIGN_LEFT)
  ownerName.style:SetFontSize(FONT_SIZE.MIDDLE)
  ownerName:AddAnchor("TOPLEFT", bottomRightWidget, "TOPLEFT", 5, 21)
  ownerName:AddAnchor("TOPRIGHT", bottomRightWidget, "TOPRIGHT", 0, 0)
  ApplyTextColor(ownerName, FONT_COLOR.BLUE)
  local ownerLevel = wnd:CreateChildWidget("textbox", "ownerLevel", 0, true)
  ownerLevel:SetAutoResize(true)
  ownerLevel:SetExtent(200, FONT_SIZE.MIDDLE)
  ownerLevel.style:SetAlign(ALIGN_LEFT)
  ownerLevel.style:SetFontSize(FONT_SIZE.MIDDLE)
  ownerLevel:AddAnchor("TOPLEFT", ownerName, "BOTTOMLEFT", 0, 13)
  ApplyTextColor(ownerLevel, FONT_COLOR.BLUE)
  local ownerExpedition = wnd:CreateChildWidget("label", "ownerExpedition", 0, true)
  ownerExpedition:SetAutoResize(true)
  ownerExpedition:SetHeight(FONT_SIZE.MIDDLE)
  ownerExpedition.style:SetAlign(ALIGN_LEFT)
  ownerExpedition.style:SetFontSize(FONT_SIZE.MIDDLE)
  ownerExpedition:AddAnchor("TOPLEFT", ownerLevel, "BOTTOMLEFT", 0, 12)
  ownerExpedition:AddAnchor("TOPRIGHT", ownerLevel, "TOPRIGHT", 0, 0)
  ApplyTextColor(ownerExpedition, FONT_COLOR.BLUE)
  local bg = CreateContentBackground(wnd, "TYPE2", "orange")
  bg:AddAnchor("TOPLEFT", ownerExpedition, "BOTTOMLEFT", -8, 10)
  bg:AddAnchor("BOTTOMRIGHT", bottomRightWidget, "BOTTOMRIGHT", 4, 0)
  local guide = wnd:CreateChildWidget("textbox", "guide", 0, true)
  guide:SetAutoResize(true)
  guide:SetHeight(FONT_SIZE.MIDDLE)
  guide:SetLineSpace(TEXTBOX_LINE_SPACE.SMALL)
  guide.style:SetAlign(ALIGN_TOP_LEFT)
  guide.style:SetFontSize(FONT_SIZE.MIDDLE)
  guide:AddAnchor("TOPLEFT", bg, "TOPLEFT", 10, 10)
  guide:AddAnchor("BOTTOMRIGHT", bg, "BOTTOMRIGHT", -10, -10)
  ApplyTextColor(guide, FONT_COLOR.DEFAULT)
  local roleRadioBoxes = CreateRadioGroup("roleRadioBoxes", wnd, "grid")
  roleRadioBoxes:AddAnchor("TOPLEFT", guide, "BOTTOMLEFT", -5, 24)
  roleRadioBoxes:SetWidth(bottomRightWidget:GetWidth())
  roleRadioBoxes:SetData(W_MODULE:GetRoleInfo())
  roleRadioBoxes:Check(1)
  wnd.roleRadioBoxes = roleRadioBoxes
  local questionTextbox = wnd:CreateChildWidget("textbox", "questionLabel", 0, true)
  questionTextbox:SetAutoResize(true)
  questionTextbox:SetHeight(FONT_SIZE.LARGE)
  questionTextbox.style:SetAlign(ALIGN_CENTER)
  questionTextbox.style:SetFontSize(FONT_SIZE.LARGE)
  questionTextbox:AddAnchor("TOPLEFT", wnd, "BOTTOMLEFT", 0, -115)
  questionTextbox:AddAnchor("BOTTOMRIGHT", wnd, "BOTTOMRIGHT", 0, -70)
  ApplyTextColor(questionTextbox, FONT_COLOR.DEFAULT)
  questionTextbox:SetText(GetCommonText("raid_applicant_question"))
  wnd.questionTextbox = questionTextbox
  local registerButton = wnd:CreateChildWidget("button", "registerButton", 0, true)
  registerButton:SetText(GetCommonText("apply"))
  ApplyButtonSkin(registerButton, BUTTON_BASIC.DEFAULT)
  registerButton:AddAnchor("BOTTOMLEFT", wnd, "BOTTOMLEFT", wnd:GetWidth() / 2 - registerButton:GetWidth(), -sideMargin)
  local cancelButton = wnd:CreateChildWidget("button", "cancelButton", 0, true)
  cancelButton:SetText(GetCommonText("cancel"))
  ApplyButtonSkin(cancelButton, BUTTON_BASIC.DEFAULT)
  cancelButton:AddAnchor("BOTTOMLEFT", registerButton, "BOTTOMRIGHT", 0, 0)
  return wnd
end
