function SetViewOfRaidApplicantAccept()
  local sideMargin, titleMargin, bottomMargin = GetWindowMargin()
  local wnd = CreateWindow("raidApplicantAccept", "UIParent")
  wnd:SetExtent(430, 268)
  wnd:AddAnchor("CENTER", "UIParent", 0, 0)
  wnd:SetTitle(GetCommonText("raid_join"))
  local questLabel = wnd:CreateChildWidget("label", "recruitTypeLabal", 0, true)
  questLabel:SetWidth(391)
  questLabel:SetHeight(FONT_SIZE.LARGE)
  questLabel.style:SetAlign(ALIGN_CENTER)
  questLabel.style:SetFontSize(FONT_SIZE.LARGE)
  questLabel:AddAnchor("TOPLEFT", wnd, "TOPLEFT", 20, titleMargin)
  questLabel:SetText(GetCommonText("raid_join_question"))
  ApplyTextColor(questLabel, FONT_COLOR.DEFAULT)
  local empty = wnd:CreateChildWidget("emptywidget", "empty", 0, false)
  empty:SetExtent(391, 117)
  empty:AddAnchor("TOPLEFT", questLabel, "BOTTOMLEFT", 0, 11)
  local leftWidth = 173
  local subTypeTextbox = wnd:CreateChildWidget("textbox", "subTypeTextbox", 0, true)
  subTypeTextbox:SetExtent(leftWidth, FONT_SIZE.MIDDLE)
  subTypeTextbox:SetHeight(FONT_SIZE.MIDDLE)
  subTypeTextbox.style:SetFontSize(FONT_SIZE.MIDDLE)
  subTypeTextbox.style:SetAlign(ALIGN_CENTER)
  subTypeTextbox:AddAnchor("TOPLEFT", empty, "TOPLEFT", 0, 10)
  ApplyTextColor(subTypeTextbox, FONT_COLOR.DEFAULT)
  subTypeTextbox:SetText(GetCommonText("raid_type"))
  local requireLevelTextbox = wnd:CreateChildWidget("textbox", "requireLevelTextbox", 0, true)
  requireLevelTextbox:SetExtent(leftWidth, FONT_SIZE.MIDDLE)
  requireLevelTextbox:SetHeight(FONT_SIZE.MIDDLE)
  requireLevelTextbox.style:SetFontSize(FONT_SIZE.MIDDLE)
  requireLevelTextbox.style:SetAlign(ALIGN_CENTER)
  requireLevelTextbox:AddAnchor("TOPLEFT", subTypeTextbox, "BOTTOMLEFT", 0, 8)
  ApplyTextColor(requireLevelTextbox, FONT_COLOR.DEFAULT)
  requireLevelTextbox:SetText(GetCommonText("raid_level_require"))
  local departureTimeTextbox = wnd:CreateChildWidget("textbox", "departureTimeTextbox", 0, true)
  departureTimeTextbox:SetExtent(leftWidth, FONT_SIZE.MIDDLE)
  departureTimeTextbox:SetHeight(FONT_SIZE.MIDDLE)
  departureTimeTextbox.style:SetFontSize(FONT_SIZE.MIDDLE)
  departureTimeTextbox.style:SetAlign(ALIGN_CENTER)
  departureTimeTextbox:AddAnchor("TOPLEFT", requireLevelTextbox, "BOTTOMLEFT", 0, 8)
  ApplyTextColor(departureTimeTextbox, FONT_COLOR.DEFAULT)
  departureTimeTextbox:SetText(GetCommonText("raid_departure_time"))
  local ownerLevelTextbox = wnd:CreateChildWidget("textbox", "ownerLevelTextbox", 0, true)
  ownerLevelTextbox:SetExtent(leftWidth, FONT_SIZE.MIDDLE)
  ownerLevelTextbox:SetHeight(FONT_SIZE.MIDDLE)
  ownerLevelTextbox.style:SetFontSize(FONT_SIZE.MIDDLE)
  ownerLevelTextbox.style:SetAlign(ALIGN_CENTER)
  ownerLevelTextbox:AddAnchor("TOPLEFT", departureTimeTextbox, "BOTTOMLEFT", 0, 8)
  ApplyTextColor(ownerLevelTextbox, FONT_COLOR.DEFAULT)
  ownerLevelTextbox:SetText(GetCommonText("raid_recruit_owner_level"))
  local ownerNameTextbox = wnd:CreateChildWidget("textbox", "ownerNameTextbox", 0, true)
  ownerNameTextbox:SetExtent(leftWidth, FONT_SIZE.MIDDLE)
  ownerNameTextbox:SetHeight(FONT_SIZE.MIDDLE)
  ownerNameTextbox.style:SetFontSize(FONT_SIZE.MIDDLE)
  ownerNameTextbox.style:SetAlign(ALIGN_CENTER)
  ownerNameTextbox:AddAnchor("TOPLEFT", ownerLevelTextbox, "BOTTOMLEFT", 0, 8)
  ApplyTextColor(ownerNameTextbox, FONT_COLOR.DEFAULT)
  ownerNameTextbox:SetText(GetCommonText("raid_recruit_owner_name"))
  local rightWidth = 220
  local subType = wnd:CreateChildWidget("textbox", "subType", 0, true)
  subType:SetExtent(rightWidth, FONT_SIZE.MIDDLE)
  subType:SetHeight(FONT_SIZE.MIDDLE)
  subType.style:SetFontSize(FONT_SIZE.MIDDLE)
  subType.style:SetAlign(ALIGN_LEFT)
  subType:AddAnchor("TOPLEFT", subTypeTextbox, "TOPRIGHT", 2, 0)
  ApplyTextColor(subType, FONT_COLOR.BLUE)
  subType:SetText(GetCommonText("raid_type"))
  local requireLevel = wnd:CreateChildWidget("textbox", "requireLevel", 0, true)
  requireLevel:SetExtent(rightWidth, FONT_SIZE.MIDDLE)
  requireLevel:SetHeight(FONT_SIZE.MIDDLE)
  requireLevel.style:SetFontSize(FONT_SIZE.MIDDLE)
  requireLevel.style:SetAlign(ALIGN_LEFT)
  requireLevel:AddAnchor("TOPLEFT", subType, "BOTTOMLEFT", 0, 8)
  ApplyTextColor(requireLevel, FONT_COLOR.BLUE)
  requireLevel:SetText(GetCommonText("raid_type"))
  local departureTime = wnd:CreateChildWidget("textbox", "departureTime", 0, true)
  departureTime:SetExtent(rightWidth, FONT_SIZE.MIDDLE)
  departureTime:SetHeight(FONT_SIZE.MIDDLE)
  departureTime.style:SetFontSize(FONT_SIZE.MIDDLE)
  departureTime.style:SetAlign(ALIGN_LEFT)
  departureTime:AddAnchor("TOPLEFT", requireLevel, "BOTTOMLEFT", 0, 8)
  ApplyTextColor(departureTime, FONT_COLOR.BLUE)
  departureTime:SetText(GetCommonText("raid_type"))
  local ownerLevel = wnd:CreateChildWidget("textbox", "ownerLevel", 0, true)
  ownerLevel:SetExtent(rightWidth, FONT_SIZE.MIDDLE)
  ownerLevel:SetHeight(FONT_SIZE.MIDDLE)
  ownerLevel.style:SetFontSize(FONT_SIZE.MIDDLE)
  ownerLevel.style:SetAlign(ALIGN_LEFT)
  ownerLevel:AddAnchor("TOPLEFT", departureTime, "BOTTOMLEFT", 0, 8)
  ApplyTextColor(ownerLevel, FONT_COLOR.BLUE)
  ownerLevel:SetText(GetCommonText("raid_type"))
  local ownerName = wnd:CreateChildWidget("textbox", "ownerName", 0, true)
  ownerName:SetExtent(rightWidth, FONT_SIZE.MIDDLE)
  ownerName:SetHeight(FONT_SIZE.MIDDLE)
  ownerName.style:SetFontSize(FONT_SIZE.MIDDLE)
  ownerName.style:SetAlign(ALIGN_LEFT)
  ownerName:AddAnchor("TOPLEFT", ownerLevel, "BOTTOMLEFT", 0, 8)
  ApplyTextColor(ownerName, FONT_COLOR.BLUE)
  ownerName:SetText(GetCommonText("raid_type"))
  local okButton = wnd:CreateChildWidget("button", "okButton", 0, true)
  okButton:SetText(GetCommonText("ok"))
  ApplyButtonSkin(okButton, BUTTON_BASIC.DEFAULT)
  okButton:AddAnchor("BOTTOMLEFT", wnd, "BOTTOMLEFT", wnd:GetWidth() / 2 - okButton:GetWidth(), -sideMargin)
  local cancelButton = wnd:CreateChildWidget("button", "cancelButton", 0, true)
  cancelButton:SetText(GetCommonText("cancel"))
  ApplyButtonSkin(cancelButton, BUTTON_BASIC.DEFAULT)
  cancelButton:AddAnchor("BOTTOMLEFT", okButton, "BOTTOMRIGHT", 0, 0)
  local bg = CreateContentBackground(wnd, "TYPE2", "brown", "artwork")
  bg:SetExtent(leftWidth, 117)
  bg:AddAnchor("TOPLEFT", empty, "TOPLEFT", 0, 0)
  return wnd
end
