local RAID_RECRUIT_PER_MINUTE = 10
function SetViewOfRaidRecruitment(id, parent)
  local sideMargin, titleMargin, bottomMargin = GetWindowMargin()
  local wnd = CreateWindow(id, "UIParent")
  wnd:SetExtent(510, 569)
  wnd:AddAnchor("CENTER", "UIParent", 0, 0)
  wnd:SetTitle(GetCommonText("raid_recruit"))
  wnd:Show(true)
  parent.recruitmentWnd = wnd
  local emptyBottomMagin = bottomMargin - 110
  local bottomWidget_y = 5
  local leftWidget = wnd:CreateChildWidget("emptywidget", "emptywidget", 0, false)
  leftWidget:AddAnchor("TOPLEFT", wnd, "TOPLEFT", sideMargin, titleMargin)
  leftWidget:AddAnchor("BOTTOMRIGHT", wnd, "BOTTOMRIGHT", -(wnd:GetWidth() / 3) * 2, emptyBottomMagin)
  local topLeftWidget = wnd:CreateChildWidget("emptywidget", "topLeftWidget", 0, false)
  topLeftWidget:AddAnchor("TOPLEFT", leftWidget, "TOPLEFT", 0, 0)
  topLeftWidget:AddAnchor("BOTTOMRIGHT", leftWidget, "BOTTOMRIGHT", 0, -(leftWidget:GetHeight() / 2))
  local bottomLeftWidget = wnd:CreateChildWidget("emptywidget", "bottomLeftWidget", 0, false)
  bottomLeftWidget:AddAnchor("TOPLEFT", topLeftWidget, "BOTTOMLEFT", 0, bottomWidget_y)
  bottomLeftWidget:AddAnchor("BOTTOMRIGHT", leftWidget, "BOTTOMRIGHT", 0, 0)
  local bg = CreateContentBackground(topLeftWidget, "TYPE2", "brown")
  bg:AddAnchor("TOPLEFT", topLeftWidget, 0, 0)
  bg:AddAnchor("BOTTOMRIGHT", topLeftWidget, 0, 0)
  local bg = CreateContentBackground(bottomLeftWidget, "TYPE2", "brown")
  bg:AddAnchor("TOPLEFT", bottomLeftWidget, 0, 0)
  bg:AddAnchor("BOTTOMRIGHT", bottomLeftWidget, 0, 0)
  local rightWidget = wnd:CreateChildWidget("emptywidget", "rightWidget", 0, false)
  rightWidget:AddAnchor("TOPLEFT", leftWidget, "TOPRIGHT", 4, 0)
  rightWidget:AddAnchor("BOTTOMRIGHT", wnd, "BOTTOMRIGHT", -sideMargin, emptyBottomMagin)
  local topRightWidget = wnd:CreateChildWidget("emptywidget", "topRightWidget", 0, false)
  topRightWidget:AddAnchor("TOPLEFT", rightWidget, "TOPLEFT", 0, 0)
  topRightWidget:AddAnchor("BOTTOMRIGHT", rightWidget, "BOTTOMRIGHT", 0, -(rightWidget:GetHeight() / 2))
  local bottomRightWidget = wnd:CreateChildWidget("emptywidget", "bottomRightWidget", 0, false)
  bottomRightWidget:AddAnchor("TOPLEFT", topRightWidget, "BOTTOMLEFT", 0, bottomWidget_y)
  bottomRightWidget:AddAnchor("BOTTOMRIGHT", rightWidget, "BOTTOMRIGHT", 0, 0)
  local recruitTypeLabel = wnd:CreateChildWidget("label", "recruitTypeLabal", 0, true)
  recruitTypeLabel:SetAutoResize(true)
  recruitTypeLabel:SetHeight(FONT_SIZE.LARGE)
  recruitTypeLabel.style:SetAlign(ALIGN_CENTER)
  recruitTypeLabel.style:SetFontSize(FONT_SIZE.LARGE)
  recruitTypeLabel:AddAnchor("TOPLEFT", topLeftWidget, "TOPLEFT", 0, 16)
  recruitTypeLabel:AddAnchor("TOPRIGHT", topLeftWidget, "TOPRIGHT", 0, 0)
  recruitTypeLabel:SetText(GetCommonText("raid_type"))
  ApplyTextColor(recruitTypeLabel, FONT_COLOR.DEFAULT)
  local recruitType1Label = wnd:CreateChildWidget("label", "recruitType1Label", 0, true)
  recruitType1Label:SetAutoResize(true)
  recruitType1Label:SetHeight(FONT_SIZE.MIDDLE)
  recruitType1Label.style:SetAlign(ALIGN_CENTER)
  recruitType1Label.style:SetFontSize(FONT_SIZE.MIDDLE)
  recruitType1Label:AddAnchor("TOPLEFT", recruitTypeLabel, "BOTTOMLEFT", 0, 10)
  recruitType1Label:AddAnchor("TOPRIGHT", recruitTypeLabel, "TOPRIGHT", 0, 0)
  recruitType1Label:SetText(GetCommonText("raid_type_1"))
  ApplyTextColor(recruitType1Label, FONT_COLOR.DEFAULT)
  local recruitType2Label = wnd:CreateChildWidget("label", "recruitType2Label", 0, true)
  recruitType2Label:SetAutoResize(true)
  recruitType2Label:SetHeight(FONT_SIZE.MIDDLE)
  recruitType2Label.style:SetAlign(ALIGN_CENTER)
  recruitType2Label.style:SetFontSize(FONT_SIZE.MIDDLE)
  recruitType2Label:AddAnchor("TOPLEFT", recruitType1Label, "BOTTOMLEFT", 0, 18)
  recruitType2Label:AddAnchor("TOPRIGHT", recruitType1Label, "TOPRIGHT", 0, 0)
  recruitType2Label:SetText(GetCommonText("raid_type_2"))
  ApplyTextColor(recruitType2Label, FONT_COLOR.DEFAULT)
  local descriptionLabel = wnd:CreateChildWidget("textbox", "descriptionLabel", 0, true)
  descriptionLabel:SetAutoResize(true)
  descriptionLabel:SetHeight(FONT_SIZE.MIDDLE)
  descriptionLabel.style:SetAlign(ALIGN_CENTER)
  descriptionLabel.style:SetFontSize(FONT_SIZE.MIDDLE)
  descriptionLabel:AddAnchor("TOPLEFT", recruitType2Label, "BOTTOMLEFT", 0, 18)
  descriptionLabel:AddAnchor("TOPRIGHT", recruitType2Label, "TOPRIGHT", 0, 0)
  descriptionLabel:SetText(GetCommonText("raid_description"))
  ApplyTextColor(descriptionLabel, FONT_COLOR.DEFAULT)
  local typeIcon = wnd:CreateImageDrawable(TEXTURE_PATH.RAID_RECRUIT, "overlay")
  typeIcon:AddAnchor("TOPLEFT", topRightWidget, "TOPLEFT", 0, 36)
  wnd.typeIcon = typeIcon
  local typeList = X2Team:GetRaidRecruitTypeList()
  local recruitDatas = {}
  for i = 1, #typeList do
    local data = {
      text = typeList[i].name,
      value = typeList[i].type
    }
    table.insert(recruitDatas, data)
  end
  local typeComboBox = W_CTRL.CreateComboBox("typeComboBox", wnd)
  typeComboBox:SetWidth(145)
  typeComboBox:AddAnchor("LEFT", typeIcon, "RIGHT", 3, 0)
  typeComboBox:AppendItems(recruitDatas)
  local subTypeComboBox = W_CTRL.CreateComboBox("subTypeComboBox", wnd)
  subTypeComboBox:SetWidth(topRightWidget:GetWidth())
  subTypeComboBox:AddAnchor("TOPLEFT", typeIcon, "BOTTOMLEFT", 0, 8)
  subTypeComboBox:SetVisibleItemCount(10)
  local bg = CreateContentBackground(wnd, "TYPE2", "orange")
  bg:AddAnchor("TOPLEFT", subTypeComboBox, "BOTTOMLEFT", -4, 2)
  bg:AddAnchor("BOTTOMRIGHT", topRightWidget, "BOTTOMRIGHT", 4, 0)
  local descriptionTextbox = wnd:CreateChildWidget("textbox", "descriptionTextbox", 0, true)
  descriptionTextbox:SetAutoResize(true)
  descriptionTextbox:SetHeight(FONT_SIZE.LARGE)
  descriptionTextbox:SetLineSpace(TEXTBOX_LINE_SPACE.SMALL)
  descriptionTextbox.style:SetAlign(ALIGN_TOP_LEFT)
  descriptionTextbox.style:SetFontSize(FONT_SIZE.MIDDLE)
  descriptionTextbox:AddAnchor("TOPLEFT", bg, "TOPLEFT", 10, 10)
  descriptionTextbox:AddAnchor("BOTTOMRIGHT", bg, "BOTTOMRIGHT", -10, -10)
  ApplyTextColor(descriptionTextbox, FONT_COLOR.DEFAULT)
  local levelLimitLabel = wnd:CreateChildWidget("label", "levelLimitLabel", 0, true)
  levelLimitLabel:SetAutoResize(true)
  levelLimitLabel:SetHeight(FONT_SIZE.LARGE)
  levelLimitLabel.style:SetAlign(ALIGN_CENTER)
  levelLimitLabel.style:SetFontSize(FONT_SIZE.LARGE)
  levelLimitLabel:AddAnchor("TOPLEFT", bottomLeftWidget, "TOPLEFT", 0, 12)
  levelLimitLabel:AddAnchor("TOPRIGHT", bottomLeftWidget, "TOPRIGHT", 0, 0)
  levelLimitLabel:SetText(GetCommonText("raid_level_limit"))
  ApplyTextColor(levelLimitLabel, FONT_COLOR.DEFAULT)
  local headcountLabel = wnd:CreateChildWidget("label", "headcountLabel", 0, true)
  headcountLabel:SetAutoResize(true)
  headcountLabel:SetHeight(FONT_SIZE.LARGE)
  headcountLabel.style:SetAlign(ALIGN_CENTER)
  headcountLabel.style:SetFontSize(FONT_SIZE.LARGE)
  headcountLabel:AddAnchor("TOPLEFT", levelLimitLabel, "BOTTOMLEFT", 0, 16)
  headcountLabel:AddAnchor("TOPRIGHT", levelLimitLabel, "TOPRIGHT", 0, 0)
  headcountLabel:SetText(GetCommonText("raid_volume_recruitment"))
  ApplyTextColor(headcountLabel, FONT_COLOR.DEFAULT)
  local departureTimeLabel = wnd:CreateChildWidget("label", "departureTimeLabel ", 0, true)
  departureTimeLabel:SetAutoResize(true)
  departureTimeLabel:SetHeight(FONT_SIZE.LARGE)
  departureTimeLabel.style:SetAlign(ALIGN_CENTER)
  departureTimeLabel.style:SetFontSize(FONT_SIZE.LARGE)
  departureTimeLabel:AddAnchor("TOPLEFT", headcountLabel, "BOTTOMLEFT", 0, 16)
  departureTimeLabel:AddAnchor("TOPRIGHT", headcountLabel, "TOPRIGHT", 0, 0)
  departureTimeLabel:SetText(GetCommonText("raid_departure_time"))
  ApplyTextColor(departureTimeLabel, FONT_COLOR.DEFAULT)
  local joinTypeLabel = wnd:CreateChildWidget("label", "joinTypeLabel", 0, true)
  joinTypeLabel:SetAutoResize(true)
  joinTypeLabel:SetHeight(FONT_SIZE.LARGE)
  joinTypeLabel.style:SetAlign(ALIGN_CENTER)
  joinTypeLabel.style:SetFontSize(FONT_SIZE.LARGE)
  joinTypeLabel:AddAnchor("TOPLEFT", departureTimeLabel, "BOTTOMLEFT", 0, 16)
  joinTypeLabel:AddAnchor("TOPRIGHT", departureTimeLabel, "TOPRIGHT", 0, 0)
  joinTypeLabel:SetText(GetCommonText("raid_join_type"))
  ApplyTextColor(joinTypeLabel, FONT_COLOR.DEFAULT)
  local expenseLabel = wnd:CreateChildWidget("label", "expenseLabel", 0, true)
  expenseLabel:SetAutoResize(true)
  expenseLabel:SetHeight(FONT_SIZE.LARGE)
  expenseLabel.style:SetAlign(ALIGN_CENTER)
  expenseLabel.style:SetFontSize(FONT_SIZE.LARGE)
  expenseLabel:AddAnchor("TOPLEFT", joinTypeLabel, "BOTTOMLEFT", 0, 16)
  expenseLabel:AddAnchor("TOPRIGHT", joinTypeLabel, "TOPRIGHT", 0, 0)
  expenseLabel:SetText(GetCommonText("raid_promotional_expenses"))
  ApplyTextColor(expenseLabel, FONT_COLOR.DEFAULT)
  wnd.expenseLabel = expenseLabel
  local levelComboBox = W_CTRL.CreateComboBox("levelComboBox", wnd)
  levelComboBox:SetWidth(175)
  levelComboBox:SetVisibleItemCount(5)
  levelComboBox:AddAnchor("TOPLEFT", bottomRightWidget, "TOPLEFT", 0, 6)
  local headcountList = X2Team:GetRaidRecruitHeadcountList()
  local headcountDatas = {}
  for i = 1, #headcountList do
    local data = {
      text = tostring(headcountList[i]),
      value = headcountList[i]
    }
    table.insert(headcountDatas, data)
  end
  local headcountComboBox = W_CTRL.CreateComboBox("headcountComboBox", wnd)
  headcountComboBox:SetWidth(84)
  headcountComboBox:AppendItems(headcountDatas)
  headcountComboBox:AddAnchor("TOPRIGHT", levelComboBox, "BOTTOMRIGHT", 0, 6)
  local raidMemberCountLabel = wnd:CreateChildWidget("label", "raidMemberCountLabel", 0, true)
  raidMemberCountLabel:SetAutoResize(true)
  raidMemberCountLabel:SetHeight(FONT_SIZE.LARGE)
  raidMemberCountLabel.style:SetAlign(ALIGN_CENTER)
  raidMemberCountLabel.style:SetFontSize(FONT_SIZE.LARGE)
  raidMemberCountLabel:AddAnchor("RIGHT", headcountComboBox, "LEFT", -10, 0)
  ApplyTextColor(raidMemberCountLabel, FONT_COLOR.DEFAULT)
  local DEFAULT_FORMAT_FILTER = FORMAT_FILTER.HOUR + FORMAT_FILTER.MINUTE
  local timeDatas = {}
  local timeMap = {}
  for hour = 0, 23 do
    for minute = 0, 59, RAID_RECRUIT_PER_MINUTE do
      local data = {value = index}
      local info = {}
      info.hour = hour
      info.minute = minute
      data.text = locale.time.GetDateToDateFormat(info, DEFAULT_FORMAT_FILTER)
      local time = {hour = hour, minute = minute}
      table.insert(timeDatas, data)
      table.insert(timeMap, time)
    end
  end
  wnd.timeMap = timeMap
  local timeComboBox = W_CTRL.CreateComboBox("timeComboBox", wnd)
  timeComboBox:SetWidth(levelComboBox:GetWidth())
  timeComboBox:AppendItems(timeDatas)
  timeComboBox:SetVisibleItemCount(60 / RAID_RECRUIT_PER_MINUTE)
  timeComboBox:AddAnchor("TOPRIGHT", headcountComboBox, "BOTTOMRIGHT", 0, 6)
  local joinTexts = GetRiadJoinTextList(true)
  local joinRadioBoxes = CreateRadioGroup("recruitmentJoinRadioBoxes", wnd, "horizen")
  joinRadioBoxes:SetData(joinTexts)
  joinRadioBoxes:Check(1, false)
  joinRadioBoxes:AddAnchor("TOPLEFT", timeComboBox, "BOTTOMLEFT", 0, 10)
  wnd.joinRadioBoxes = joinRadioBoxes
  local expense = W_MODULE:Create("expense", wnd, WINDOW_MODULE_TYPE.VALUE_BOX)
  expense:AddAnchor("TOPLEFT", joinRadioBoxes, "BOTTOMLEFT", 2, 12)
  local guideLabel = wnd:CreateChildWidget("label", "guideLabel ", 0, true)
  guideLabel:SetAutoResize(true)
  guideLabel:SetHeight(FONT_SIZE.LARGE)
  guideLabel.style:SetAlign(ALIGN_LEFT)
  guideLabel.style:SetFontSize(FONT_SIZE.LARGE)
  guideLabel:AddAnchor("TOPLEFT", leftWidget, "BOTTOMLEFT", 0, 18)
  guideLabel:SetText(GetCommonText("raid_guide"))
  ApplyTextColor(guideLabel, FONT_COLOR.DEFAULT)
  local guideEdit = W_CTRL.CreateMultiLineEdit("guideEdit", wnd)
  guideEdit:SetExtent(471, 59)
  guideEdit:SetInset(10, 10, 15, 10)
  guideEdit.textLength = 50
  guideEdit:SetMaxTextLength(guideEdit.textLength)
  guideEdit:AddAnchor("TOPLEFT", guideLabel, "BOTTOMLEFT", 0, 6)
  ApplyTextColor(guideEdit, FONT_COLOR.DEFAULT)
  local guideTextLenth = wnd:CreateChildWidget("label", "guideTextLenth", 0, true)
  guideTextLenth:SetHeight(FONT_SIZE.MIDDLE)
  guideTextLenth:SetAutoResize(true)
  guideTextLenth.style:SetAlign(ALIGN_RIGHT)
  guideTextLenth.style:SetFontSize(FONT_SIZE.MIDDLE)
  guideTextLenth:AddAnchor("BOTTOMRIGHT", guideEdit, "TOPRIGHT", -4, -2)
  ApplyTextColor(guideTextLenth, FONT_COLOR.DEFAULT)
  local bg = CreateContentBackground(guideEdit, "TYPE2", "orange")
  bg:AddAnchor("TOPLEFT", guideEdit, "TOPLEFT", -5, -5)
  bg:AddAnchor("BOTTOMRIGHT", guideEdit, "BOTTOMRIGHT", 0, 0)
  local registerButton = wnd:CreateChildWidget("button", "registerButton", 0, true)
  registerButton:SetText(GetCommonText("register"))
  ApplyButtonSkin(registerButton, BUTTON_BASIC.DEFAULT)
  registerButton:AddAnchor("BOTTOMLEFT", wnd, "BOTTOMLEFT", wnd:GetWidth() / 2 - registerButton:GetWidth(), -sideMargin)
  local cancelButton = wnd:CreateChildWidget("button", "cancelButton", 0, true)
  cancelButton:SetText(GetCommonText("cancel"))
  ApplyButtonSkin(cancelButton, BUTTON_BASIC.DEFAULT)
  cancelButton:AddAnchor("BOTTOMLEFT", registerButton, "BOTTOMRIGHT", 0, 0)
  return wnd
end
