targetEquippedItem = CreateWindow("targetEquippedItem", "UIParent")
targetEquippedItem:SetExtent(430, 640)
targetEquippedItem:SetTitle(GetCommonText("target_equipments_wnd"))
targetEquippedItem.slot = {}
local screenHeight = UIParent:GetScreenHeight()
local hudHeight = 60
local slotHeight = 440
targetEquippedItem:AddAnchor("TOP", "UIParent", "TOP", 0, (screenHeight - slotHeight - hudHeight) * 0.5)
targetEquippedItem.leftSlots = targetEquippedItem:CreateChildWidget("emptyWidget", "leftSlots", 0, true)
targetEquippedItem.leftSlots:SetExtent(ICON_SIZE.DEFAULT, 485)
targetEquippedItem.leftSlots:AddAnchor("TOPLEFT", targetEquippedItem.titleBar, "BOTTOM", -200, 45)
targetEquippedItem.rightSlots = targetEquippedItem:CreateChildWidget("emptyWidget", "rightSlots", 0, true)
targetEquippedItem.rightSlots:SetExtent(ICON_SIZE.DEFAULT, 485)
targetEquippedItem.rightSlots:AddAnchor("TOPRIGHT", targetEquippedItem.titleBar, "BOTTOM", 200, 45)
targetEquippedItem.modelView = CreateModelview("modelview", targetEquippedItem)
targetEquippedItem.modelView:AddAnchor("TOP", targetEquippedItem.titleBar, "BOTTOM", 0, 50)
targetEquippedItem.modelView.rotateRight:AddAnchor("LEFT", targetEquippedItem.modelView, 5, 0)
targetEquippedItem.modelView.rotateLeft:AddAnchor("RIGHT", targetEquippedItem.modelView, -5, 0)
local gearScoreAnchorPos = -16
local targetNameAnchorPos = gearScoreAnchorPos - FONT_SIZE.LARGE - 5
targetEquippedItem.targetName = targetEquippedItem:CreateChildWidget("label", "targetName", 0, true)
targetEquippedItem.targetName:SetExtent(targetEquippedItem:GetWidth() - 110, FONT_SIZE.LARGE)
targetEquippedItem.targetName:AddAnchor("BOTTOM", targetEquippedItem, "BOTTOM", 0, targetNameAnchorPos)
targetEquippedItem.targetName.style:SetAlign(ALIGN_CENTER)
targetEquippedItem.targetName.style:SetFontSize(FONT_SIZE.LARGE)
ApplyTextColor(targetEquippedItem.targetName, FONT_COLOR.DEFAULT)
targetEquippedItem.gearScore = targetEquippedItem:CreateChildWidget("label", "gearScore", 0, true)
targetEquippedItem.gearScore:SetExtent(targetEquippedItem:GetWidth() - 110, FONT_SIZE.LARGE)
targetEquippedItem.gearScore:AddAnchor("BOTTOM", targetEquippedItem, "BOTTOM", 0, gearScoreAnchorPos)
targetEquippedItem.gearScore.style:SetAlign(ALIGN_CENTER)
targetEquippedItem.gearScore.style:SetFontSize(FONT_SIZE.LARGE)
ApplyTextColor(targetEquippedItem.gearScore, F_COLOR.GetColor("bright_blue", false))
for i = 1, #PLAYER_EQUIP_SLOTS do
  local parent = IsLeftSide(i) and targetEquippedItem.leftSlots or targetEquippedItem.rightSlots
  local button = CreateItemIconButton("targetEquippedItem.slot." .. i, parent, "constant")
  AddOnUpdateCooldown(button, "action")
  button:SetExtent(ICON_SIZE.DEFAULT, ICON_SIZE.DEFAULT)
  targetEquippedItem.slot[i] = button
  targetEquippedItem.slot[i].back:SetColor(1, 1, 1, 1)
  F_SLOT.ApplySlotSkin(targetEquippedItem.slot[i], targetEquippedItem.slot[i].back, SLOT_STYLE.EQUIP_ITEM[i])
end
targetEquippedItem.slot[21]:AddAnchor("TOP", targetEquippedItem.titleBar, "BOTTOM", 0, 0)
targetEquippedItem.slot[1]:AddAnchor("TOPLEFT", targetEquippedItem.leftSlots, 0, 0)
targetEquippedItem.slot[3]:AddAnchor("TOPLEFT", targetEquippedItem.leftSlots, 0, 48)
targetEquippedItem.slot[4]:AddAnchor("TOPLEFT", targetEquippedItem.leftSlots, 0, 96)
targetEquippedItem.slot[8]:AddAnchor("TOPLEFT", targetEquippedItem.leftSlots, 0, 144)
targetEquippedItem.slot[6]:AddAnchor("TOPLEFT", targetEquippedItem.leftSlots, 0, 192)
targetEquippedItem.slot[9]:AddAnchor("TOPLEFT", targetEquippedItem.leftSlots, 0, 269)
targetEquippedItem.slot[5]:AddAnchor("TOPLEFT", targetEquippedItem.leftSlots, 0, 317)
targetEquippedItem.slot[7]:AddAnchor("TOPLEFT", targetEquippedItem.leftSlots, 0, 365)
targetEquippedItem.slot[14]:Show(false)
targetEquippedItem.slot[15]:AddAnchor("TOPLEFT", targetEquippedItem.leftSlots, 0, 442)
targetEquippedItem.slot[2]:AddAnchor("TOPRIGHT", targetEquippedItem.rightSlots, 0, 0)
targetEquippedItem.slot[10]:AddAnchor("TOPRIGHT", targetEquippedItem.rightSlots, 0, 48)
targetEquippedItem.slot[11]:AddAnchor("TOPRIGHT", targetEquippedItem.rightSlots, 0, 96)
targetEquippedItem.slot[12]:AddAnchor("TOPRIGHT", targetEquippedItem.rightSlots, 0, 144)
targetEquippedItem.slot[13]:AddAnchor("TOPRIGHT", targetEquippedItem.rightSlots, 0, 192)
targetEquippedItem.slot[16]:AddAnchor("TOPRIGHT", targetEquippedItem.rightSlots, 0, 250)
targetEquippedItem.slot[17]:AddAnchor("TOPRIGHT", targetEquippedItem.rightSlots, 0, 298)
targetEquippedItem.slot[18]:AddAnchor("TOPRIGHT", targetEquippedItem.rightSlots, 0, 346)
targetEquippedItem.slot[19]:AddAnchor("TOPRIGHT", targetEquippedItem.rightSlots, 0, 394)
targetEquippedItem.slot[20]:AddAnchor("TOPRIGHT", targetEquippedItem.rightSlots, 0, 442)
