local sideMargin, titleMargin, bottomMargin = GetWindowMargin("popup")
function SetViewOfTerritoryFrame(window)
  local contentWidth = window:GetWidth()
  local defaultInfo = window:CreateChildWidget("textbox", "defaultInfo", 0, true)
  defaultInfo:Show(true)
  defaultInfo:SetExtent(contentWidth, 60)
  defaultInfo:AddAnchor("TOPLEFT", window, 0, sideMargin * 1.5)
  defaultInfo:SetInset(10, 0, 10, 0)
  defaultInfo:SetLineSpace(TEXTBOX_LINE_SPACE.LARGE)
  defaultInfo.style:SetAlign(ALIGN_LEFT)
  defaultInfo.style:SetSnap(true)
  ApplyTextColor(defaultInfo, FONT_COLOR.TITLE)
  local bg = CreateContentBackground(defaultInfo, "TYPE2", "brown")
  bg:AddAnchor("TOPLEFT", defaultInfo, 0, -sideMargin / 1.5)
  bg:AddAnchor("BOTTOMRIGHT", defaultInfo, 5, sideMargin / 1.5)
  local peaceMoney = window:CreateChildWidget("textbox", "peaceMoney", 0, true)
  peaceMoney:SetExtent(150, FONT_SIZE.MIDDLE)
  peaceMoney:AddAnchor("BOTTOMRIGHT", defaultInfo, -5, 0)
  peaceMoney.style:SetAlign(ALIGN_RIGHT)
  ApplyTextColor(peaceMoney, FONT_COLOR.BLUE)
  local peaceAAPoint = window:CreateChildWidget("textbox", "peaceAAPoint", 0, true)
  peaceAAPoint:SetExtent(150, FONT_SIZE.MIDDLE)
  local isConvertTaxItemToAAPoint = X2House:IsConvertTaxItemToAAPoint()
  if F_MONEY.currency.houseTax == CURRENCY_GOLD and isConvertTaxItemToAAPoint == false then
    peaceAAPoint:AddAnchor("BOTTOMRIGHT", defaultInfo, -5, 0)
  else
    peaceAAPoint:AddAnchor("BOTTOMRIGHT", peaceMoney, "TOPRIGHT", 0, -5)
  end
  peaceAAPoint.style:SetAlign(ALIGN_RIGHT)
  ApplyTextColor(peaceAAPoint, FONT_COLOR.BLUE)
  local peaceMoneyTitle = window:CreateChildWidget("label", "peaceMoneyTitle", 0, false)
  peaceMoneyTitle:SetAutoResize(true)
  peaceMoneyTitle:SetHeight(FONT_SIZE.XLARGE)
  peaceMoneyTitle:AddAnchor("BOTTOMRIGHT", peaceAAPoint, "TOPRIGHT", 0, -5)
  peaceMoneyTitle.style:SetFont(FONT_PATH.LEEYAGI, FONT_SIZE.XLARGE)
  peaceMoneyTitle.style:SetAlign(ALIGN_RIGHT)
  ApplyTextColor(peaceMoneyTitle, FONT_COLOR.DEFAULT)
  peaceMoneyTitle:SetText(locale.territory.peaceMoney)
  local deco = peaceMoney:CreateDrawable(TEXTURE_PATH.TERRITORY, "deco", "background")
  deco:AddAnchor("BOTTOMRIGHT", peaceMoneyTitle, 10, 18)
  local taxRateWindow = window:CreateChildWidget("emptywidget", "taxRateWindow", 0, true)
  taxRateWindow:Show(true)
  taxRateWindow:SetExtent(contentWidth, 60)
  taxRateWindow:AddAnchor("TOPLEFT", defaultInfo, "BOTTOMLEFT", 0, sideMargin * 1.8)
  taxRateWindow.titleStyle:SetSnap(true)
  taxRateWindow.titleStyle:SetFontSize(FONT_SIZE.LARGE)
  taxRateWindow.titleStyle:SetAlign(ALIGN_TOP_LEFT)
  ApplyTitleFontColor(taxRateWindow, FONT_COLOR.TITLE)
  local taxRateSlider = CreateSlider(window:GetId() .. ".taxRateSlider", window)
  taxRateSlider:AddAnchor("TOPLEFT", taxRateWindow, 0, sideMargin + 5)
  taxRateSlider:SetMinMaxValues(0, 50)
  taxRateSlider:UseWheel()
  window.taxRateSlider = taxRateSlider
  local currentTaxRate = window:CreateChildWidget("label", "currentTaxRate", 0, true)
  currentTaxRate:SetExtent(50, FONT_SIZE.XLARGE)
  currentTaxRate:AddAnchor("LEFT", taxRateSlider, "RIGHT", 8, 0)
  ApplyTextColor(currentTaxRate, FONT_COLOR.BLUE)
  currentTaxRate.style:SetSnap(true)
  currentTaxRate.style:SetFontSize(FONT_SIZE.XLARGE)
  taxRateSlider:SetWidth(contentWidth - currentTaxRate:GetWidth() - sideMargin / 2)
  local bg = CreateContentBackground(currentTaxRate, "TYPE2", "blue")
  bg:AddAnchor("TOPLEFT", currentTaxRate, -5, -sideMargin / 2)
  bg:AddAnchor("BOTTOMRIGHT", currentTaxRate, 5, sideMargin / 2)
  currentTaxRate.bg = bg
  local minPercent = window:CreateChildWidget("label", "minPercent", 0, true)
  minPercent:SetHeight(FONT_SIZE.MIDDLE)
  minPercent:SetAutoResize(true)
  minPercent:SetText("0%")
  minPercent:AddAnchor("TOPLEFT", taxRateSlider, "BOTTOMLEFT", 3, 5)
  ApplyTextColor(minPercent, FONT_COLOR.DEFAULT)
  minPercent.style:SetSnap(true)
  minPercent.style:SetAlign(ALIGN_LEFT)
  local maxPercent = window:CreateChildWidget("label", "maxPercent", 0, true)
  maxPercent:SetAutoResize(true)
  maxPercent:SetText("50%")
  maxPercent:SetHeight(FONT_SIZE.MIDDLE)
  maxPercent:AddAnchor("TOPRIGHT", taxRateSlider, "BOTTOMRIGHT", -3, 5)
  ApplyTextColor(maxPercent, FONT_COLOR.DEFAULT)
  maxPercent.style:SetSnap(true)
  maxPercent.style:SetAlign(ALIGN_LEFT)
  local taxationsTitle = window:CreateChildWidget("label", "taxationsTitle", 0, true)
  taxationsTitle:SetAutoResize(true)
  taxationsTitle:SetHeight(FONT_SIZE.LARGE)
  taxationsTitle:SetText(locale.territory.taxtations)
  taxationsTitle:AddAnchor("TOPLEFT", taxRateWindow, "BOTTOMLEFT", 0, sideMargin * 1.3)
  taxationsTitle.style:SetFontSize(FONT_SIZE.LARGE)
  taxationsTitle.style:SetAlign(ALIGN_LEFT)
  ApplyTextColor(taxationsTitle, FONT_COLOR.TITLE)
  local DataSetFunc = function(subItem, data, setValue)
    if setValue then
      local str = string.format([[
%s
%s]], data.desc, F_MONEY:GetTaxString(data.taxString))
      subItem.textbox:SetText(str)
    end
  end
  local LayoutSetFunc = function(frame, rowIndex, colIndex, subItem)
    W_ICON.DrawRoundDingbat(subItem)
    subItem.dingbat:RemoveAllAnchors()
    subItem.dingbat:AddAnchor("TOPLEFT", subItem, 0, 5)
    subItem:SetInset(13, 0, 0, 0)
    textbox.style:SetAlign(territoryLocale.territoryTab.listCtrlFontAlign)
    textbox.style:SetFontSize(territoryLocale.territoryTab.listCtrlFontSize)
    ApplyTextColor(textbox, FONT_COLOR.DEFAULT)
  end
  local taxationsFrame = W_CTRL.CreateScrollListCtrl("taxationsFrame", window)
  taxationsFrame:Show(true)
  taxationsFrame:SetExtent(contentWidth - 10, 200)
  taxationsFrame:AddAnchor("TOPLEFT", taxationsTitle, "BOTTOMLEFT", sideMargin / 3, sideMargin)
  taxationsFrame.scroll:RemoveAllAnchors()
  taxationsFrame.scroll:AddAnchor("TOPRIGHT", taxationsFrame, 0, 0)
  taxationsFrame.scroll:AddAnchor("BOTTOMRIGHT", taxationsFrame, 0, 0)
  local itemWidth = taxationsFrame.listCtrl:GetWidth() / 2
  taxationsFrame:InsertColumn("", itemWidth, LCCIT_TEXTBOX, DataSetFunc, nil, nil, LayoutSetFunc)
  taxationsFrame:InsertColumn("", itemWidth, LCCIT_TEXTBOX, DataSetFunc, nil, nil, LayoutSetFunc)
  taxationsFrame.listCtrl:SetColumnHeight(0)
  taxationsFrame.listCtrl.AscendingSortMark:SetVisible(false)
  taxationsFrame.listCtrl.DescendingSortMark:SetVisible(false)
  taxationsFrame:InsertRows(5, false)
  local bg = CreateContentBackground(taxationsFrame, "TYPE2", "brown")
  bg:AddAnchor("TOPLEFT", taxationsFrame, -sideMargin / 2.4, -sideMargin / 1.5)
  bg:AddAnchor("BOTTOMRIGHT", taxationsFrame, sideMargin / 2.4, sideMargin / 1.5)
  local guideIcon = W_ICON.CreateGuideIconWidget(window)
  guideIcon:AddAnchor("BOTTOMRIGHT", taxationsFrame, "TOPRIGHT", 0, -15)
  window.guideIcon = guideIcon
  local info = {
    leftButtonStr = GetUIText(OPTION_TEXT, "apply"),
    rightButtonStr = GetCommonText("cancel"),
    buttonBottomInset = 0
  }
  CreateWindowDefaultTextButtonSet(window, info)
  return window
end
